DROP TABLE IF EXISTS travel_manifests;

CREATE TABLE travel_manifests (
    manifest_id INT PRIMARY KEY,
    vehicle_id TEXT,
    departure_time TIMESTAMP,
    manifest_xml XML
);

INSERT INTO travel_manifests (manifest_id, vehicle_id, departure_time, manifest_xml) VALUES
  (1, 'SLEIGH-01', '2025-12-22 06:00:00', '<manifest><passengers><passenger><name>Nia Grant</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Sofia Kim</name><ticket_class>overnight</ticket_class><engine_check>ignored</engine_check></passenger><passenger><name>Jonah Wolfe</name><ticket_class>standard</ticket_class><snack_inventory>ignored</snack_inventory></passenger></passengers></manifest>'),
  (2, 'SLEIGH-07', '2025-12-23 13:00:00', '<manifest><passengers><passenger><name>Ravi Patel</name><ticket_class>priority</ticket_class></passenger><passenger><name>Keiko Ito</name><ticket_class>standard</ticket_class></passenger><passenger><name>Anya Pavlov</name><ticket_class>standard</ticket_class></passenger><passenger><name>Nia Grant</name><ticket_class>priority</ticket_class><snack_inventory>ignored</snack_inventory></passenger><passenger><name>Carter Lewis</name><ticket_class>priority</ticket_class><engine_check>ignored</engine_check></passenger><passenger><name>Layla Brooks</name><ticket_class>standard</ticket_class><reindeer_mood>ignored</reindeer_mood></passenger></passengers></manifest>'),
  (3, 'FLIGHT-NP-9', '2025-12-22 18:00:00', '<manifest><passengers><passenger><name>Keiko Ito</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Jonah Wolfe</name><ticket_class>priority</ticket_class></passenger><passenger><name>Diego Ramos</name><ticket_class>overnight</ticket_class><snack_inventory>ignored</snack_inventory></passenger><passenger><name>Priya Das</name><ticket_class>priority</ticket_class></passenger><passenger><name>Layla Brooks</name><ticket_class>standard</ticket_class></passenger></passengers></manifest>'),
  (4, 'TRAIN-ICE-3', '2025-12-22 18:00:00', '<manifest><reindeer_mood>low</reindeer_mood><passengers><passenger><name>Isla Torres</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Ravi Patel</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Hiro Tanaka</name><ticket_class>standard</ticket_class></passenger><passenger><name>Priya Das</name><ticket_class>priority</ticket_class></passenger></passengers></manifest>'),
  (5, 'FLIGHT-NP-9', '2025-12-22 17:00:00', '<manifest><passengers><passenger><name>Nia Grant</name><ticket_class>priority</ticket_class></passenger><passenger><name>Mateo Cruz</name><ticket_class>standard</ticket_class><snowfall_inches>ignored</snowfall_inches></passenger></passengers></manifest>'),
  (6, 'CARGO-12', '2025-12-22 15:00:00', '<manifest><passengers><passenger><name>Carter Lewis</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Sofia Kim</name><ticket_class>priority</ticket_class></passenger><passenger><name>Hiro Tanaka</name><ticket_class>priority</ticket_class></passenger><passenger><name>Lucas Ford</name><ticket_class>priority</ticket_class><snack_inventory>ignored</snack_inventory></passenger><passenger><name>Nia Grant</name><ticket_class>overnight</ticket_class></passenger></passengers></manifest>'),
  (7, 'SLEIGH-01', '2025-12-22 11:00:00', '<manifest><snack_inventory>unknown</snack_inventory><passengers><passenger><name>Priya Das</name><ticket_class>standard</ticket_class></passenger><passenger><name>Diego Ramos</name><ticket_class>standard</ticket_class></passenger><passenger><name>Lucas Ford</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Carter Lewis</name><ticket_class>overnight</ticket_class><reindeer_mood>ignored</reindeer_mood></passenger><passenger><name>Hiro Tanaka</name><ticket_class>priority</ticket_class><weather_note>ignored</weather_note></passenger><passenger><name>Zara Sheikh</name><ticket_class>overnight</ticket_class></passenger></passengers></manifest>'),
  (8, 'CARGO-12', '2025-12-23 13:00:00', '<manifest><passengers><passenger><name>Jonah Wolfe</name><ticket_class>standard</ticket_class></passenger><passenger><name>Layla Brooks</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Leo Becker</name><ticket_class>overnight</ticket_class><weather_note>ignored</weather_note></passenger><passenger><name>Ravi Patel</name><ticket_class>standard</ticket_class></passenger><passenger><name>Sofia Kim</name><ticket_class>priority</ticket_class><snack_inventory>ignored</snack_inventory></passenger><passenger><name>Elena Morales</name><ticket_class>overnight</ticket_class></passenger></passengers></manifest>'),
  (9, 'SLEIGH-01', '2025-12-23 10:00:00', '<manifest><passengers><passenger><name>Sofia Kim</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Bianca Pereira</name><ticket_class>standard</ticket_class></passenger><passenger><name>Zara Sheikh</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Elena Morales</name><ticket_class>overnight</ticket_class><reindeer_mood>ignored</reindeer_mood></passenger><passenger><name>Hiro Tanaka</name><ticket_class>priority</ticket_class></passenger><passenger><name>Keiko Ito</name><ticket_class>priority</ticket_class><snack_inventory>ignored</snack_inventory></passenger></passengers></manifest>'),
  (10, 'SLEIGH-01', '2025-12-22 21:00:00', '<manifest><snowfall_inches>low</snowfall_inches><passengers><passenger><name>Nia Grant</name><ticket_class>standard</ticket_class></passenger><passenger><name>Ava Johnson</name><ticket_class>standard</ticket_class></passenger><passenger><name>Priya Das</name><ticket_class>priority</ticket_class></passenger><passenger><name>Mateo Cruz</name><ticket_class>standard</ticket_class></passenger><passenger><name>Bianca Pereira</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Leo Becker</name><ticket_class>overnight</ticket_class></passenger></passengers></manifest>'),
  (11, 'SLEIGH-07', '2025-12-23 10:00:00', '<manifest><passengers><passenger><name>Jonah Wolfe</name><ticket_class>priority</ticket_class></passenger><passenger><name>Bianca Pereira</name><ticket_class>priority</ticket_class></passenger><passenger><name>Anya Pavlov</name><ticket_class>standard</ticket_class></passenger></passengers></manifest>'),
  (12, 'SLEIGH-01', '2025-12-22 08:00:00', '<manifest><reindeer_mood>ok</reindeer_mood><passengers><passenger><name>Ravi Patel</name><ticket_class>priority</ticket_class><snack_inventory>ignored</snack_inventory></passenger><passenger><name>Bianca Pereira</name><ticket_class>priority</ticket_class></passenger><passenger><name>Keiko Ito</name><ticket_class>standard</ticket_class></passenger></passengers></manifest>'),
  (13, 'FLIGHT-NP-9', '2025-12-22 11:00:00', '<manifest><snowfall_inches>ok</snowfall_inches><passengers><passenger><name>Nia Grant</name><ticket_class>priority</ticket_class></passenger><passenger><name>Elena Morales</name><ticket_class>standard</ticket_class></passenger></passengers></manifest>'),
  (14, 'SLEIGH-01', '2025-12-22 14:00:00', '<manifest><engine_check>high</engine_check><passengers><passenger><name>Layla Brooks</name><ticket_class>standard</ticket_class><weather_note>ignored</weather_note></passenger><passenger><name>Anya Pavlov</name><ticket_class>overnight</ticket_class></passenger><passenger><name>Keiko Ito</name><ticket_class>standard</ticket_class></passenger><passenger><name>Zara Sheikh</name><ticket_class>standard</ticket_class><engine_check>ignored</engine_check></passenger><passenger><name>Sofia Kim</name><ticket_class>overnight</ticket_class></passenger></passengers></manifest>'),
  (15, 'FLIGHT-NP-9', '2025-12-22 14:00:00', '<manifest><snowfall_inches>ok</snowfall_inches><passengers><passenger><name>Priya Das</name><ticket_class>priority</ticket_class><snowfall_inches>ignored</snowfall_inches></passenger><passenger><name>Bianca Pereira</name><ticket_class>standard</ticket_class></passenger><passenger><name>Nia Grant</name><ticket_class>standard</ticket_class></passenger></passengers></manifest>');
